name: Go
on: push

jobs:  
  build:    
    runs-on: ubuntu-latest    
    strategy:      
      matrix:        
        go-version: [ '1.23' ]    
      
    steps:      
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}        
        uses: actions/setup-go@v5        
        with:          
          go-version: ${{ matrix.go-version }}
          
      - name: Display Go version
        run: go version

      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -v ./...
        working-directory: workshop-service
      - name: Test with Go
        run: go test -json > TestResults-${{ matrix.go-version }}.json
        working-directory: workshop-service
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        working-directory: workshop-service
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json